# Generated by Django 5.0.6 on 2024-05-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('conferencia', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('nombre_completo', models.CharField(max_length=50)),
                ('abreviacion', models.CharField(max_length=10)),
            ],
        ),
    ]
