# Generated by Django 5.0.6 on 2024-06-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_jugador_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='altura',
            field=models.CharField(default='no especificado', max_length=50),
        ),
        migrations.AddField(
            model_name='jugador',
            name='dorsal',
            field=models.CharField(default='no especificado', max_length=50),
        ),
        migrations.AddField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='peso',
            field=models.CharField(default='no especificado', max_length=50),
        ),
    ]
